name       : python-pickleshare
version    : 0.7.5
release    : 4
source     :
    - https://github.com/pickleshare/pickleshare/archive/0.7.5.tar.gz : 7a691d57650dbfb1f101c52d65743f87175cea98bd85cd2a0e92c0407faf3d1c
license    : MIT
component  : programming.python
summary    : File system based database that uses python pickles.
description: |
    File system based database that uses python pickles.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-pathlib2
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
