name       : python-pickleshare
version    : 0.7.4
release    : 2
source     :
    - https://github.com/pickleshare/pickleshare/archive/0.7.4.tar.gz : a9ccf2c87c2224f26dd5b7dfd135f2472e374ae972f8d510b1b940861beb1eb4
license    : MIT
component  : programming.python
summary    : File system based database that uses python pickles.
description: |
    File system based database that uses python pickles.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-pathlib2
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
